name: Deploy Next.js to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployuser
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navegue para o diretório do seu projeto
            cd /home/deployuser/book-catalog-frontend

            # Faça um pull do código
            git pull

            # Instale novas dependências e faça o build
            npm install
            npm run build

            # Reinicie o aplicativo com PM2
            pm2 reload nextjs-app