name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            # Navega para o diretório da sua aplicação
            cd /caminho/para/seu/app # Ex: /home/ec2-user/meu-app-next
            
            # Puxa as últimas alterações ado repositório
            git pull origin main
            
            # Instala as dependências de produção
            npm install --production
            
            # Builda a aplicação
            npm run build
            
            # Reinicia a aplicação com o PM2
            pm2 restart nome-da-sua-app || pm2 start npm --name "nome-da-sua-app" -- start
